[package]
name = "code-2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = 'day1'

[[bin]]
name = 'day2'

[[bin]]
name = 'day3'

[[bin]]
name = 'day4'

[dependencies]
md5 = "0.7.0"
